# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meterusage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10meterusage.proto\x12\nmeterusage\"6\n\x0eTimestampRange\x12\x12\n\nstart_time\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\t\"1\n\x0cMeterReading\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x13\n\x0bmeter_usage\x18\x02 \x01(\x02\x32U\n\nMeterUsage\x12G\n\rGetMeterUsage\x12\x1a.meterusage.TimestampRange\x1a\x18.meterusage.MeterReading0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meterusage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMESTAMPRANGE._serialized_start=32
  _TIMESTAMPRANGE._serialized_end=86
  _METERREADING._serialized_start=88
  _METERREADING._serialized_end=137
  _METERUSAGE._serialized_start=139
  _METERUSAGE._serialized_end=224
# @@protoc_insertion_point(module_scope)
